---
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
execute: 
  echo: false
  error: false
  warning: false
params:
  # paths
  dir_app: ""
  dir_data: ""
  dir_teams: ""
  # main data file
  main_df_name: ""
---

```{r}
#| label: load parameters from RDS

params_df <- fs::path(params$dir_app, "saved_params.rds") |>
	readRDS()

```

```{r}
#| label: determine which cases to include

cases_for_report <- fs::path(
    params$dir_data,
    paste0(params$main_df_name, ".dta")
  ) |>
	haven::read_dta() |>
	dplyr::select(interview__id)

```

```{r}
#| label: load interview metadata to add to all data files

interview_actions <- fs::path(params$dir_data, "interview__actions.dta") |>
  # ingest
	haven::read_dta()

# compile supervisors and their interviewers
supervisor_interviewer <- fs::path(params$dir_teams, "team_composition.dta") |>
  # ingest
	haven::read_dta() |>
  # remove any archived users
  dplyr::filter(IsArchived == 0) |>
  # keep supervisor and interviewer columns, renaming them to match
  # names in the df of who is responsible for each interview
	dplyr::select(
    supervisor = SupervisorName,
    interviewer = UserName
  )

# inventory interviews and the interviewer responsible
interviews_who_is_responsible <- interview_actions |>
  # get the last completion event for each interview
	dplyr::group_by(interview__id, interview__key) |>
	dplyr::filter(action == 3) |>
	dplyr::filter(dplyr::row_number() == dplyr::n()) |>
  dplyr::ungroup() |>
  # keep variables
	dplyr::select(
    interview__id, interview__key,
    interviewer = originator,
    supervisor = responsible__name
  )

# create metadata on who is responsible for each interview
# - interviewer
# - supervisor (team)
supervisor_interviewer_interview <- supervisor_interviewer |>
	dplyr::left_join(
    y = interviews_who_is_responsible,
    by = c("supervisor", "interviewer")
  ) |>
	dplyr::select(supervisor, interviewer, interview__id, interview__key)
```

```{r}
#| label: load data prep and table utility functions

source("reporting_fct.R")
```

```{r}
#| label: parcels per household
#| eval: !expr '!is.null(params_df$use_parcels_per_hhold) && params_df$use_parcels_per_hhold == TRUE'
#| output: asis

cat(
  knitr::knit_child(
    text = readr::read_file("_parcels_per_hhold.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)

```

```{r}
#| label: parcel GPS measurement
#| eval: !expr '!is.null(params_df$use_parcel_gps) && params_df$use_parcel_gps == TRUE'
#| output: asis

cat(
  knitr::knit_child(
    text = readr::read_file("_parcel_gps.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)

```

```{r}
#| label: plots per parcel
#| eval: !expr '!is.null(params_df$use_plots_per_parcel) && params_df$use_plots_per_parcel == TRUE'
#| output: asis

cat(
  knitr::knit_child(
    text = readr::read_file("_plots_per_parcel.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)

```

```{r}
#| label: plot use
#| eval: !expr '!is.null(params_df$use_plot_use) && params_df$use_plot_use == TRUE'
#| output: asis

cat(
  knitr::knit_child(
    text = readr::read_file("_plot_use.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)

```

```{r}
#| label: plot GPS measurement
#| eval: !expr '!is.null(params_df$use_plot_gps) && params_df$use_plot_gps == TRUE'
#| output: asis

cat(
  knitr::knit_child(
    text = readr::read_file("_plot_gps.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)

```

```{r}
#| label: crops per plot
#| eval: !expr '!is.null(params_df$use_crops_per_plot) && params_df$use_crops_per_plot == TRUE'
#| output: asis

cat(
  knitr::knit_child(
    text = readr::read_file("_crops_per_plot.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)

```

```{r}
#| label: crop types
#| eval: !expr '!is.null(params_df$use_crop_types) && params_df$use_crop_types == TRUE'
#| output: asis

cat(
  knitr::knit_child(
    text = readr::read_file("_crop_types.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)

```

```{r}
#| label: temporary crop harvest
#| eval: !expr '!is.null(params_df$use_temp_crop_harvest) & params_df$use_temp_crop_harvest == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_temp_crop_harvest.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: temporary crop sales
#| eval: !expr '!is.null(params_df$use_temp_crop_sales) & params_df$use_temp_crop_sales == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_temp_crop_sales.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: permanent crop sales
#| eval: !expr '!is.null(params_df$use_perm_crop_sales) & params_df$use_perm_crop_sales == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_perm_crop_sales.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: livestock ownership
#| eval: !expr '!is.null(params_df$use_livestock_owership) & params_df$use_livestock_owership == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_livestock_ownership.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: cow displacement
#| eval: !expr '!is.null(params_df$use_cow_displacement) & params_df$use_cow_displacement == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_cow_displacement.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: hen displacement
#| eval: !expr '!is.null(params_df$use_hen_displacement) & params_df$use_hen_displacement == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_hen_displacement.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: milk production and sales
#| eval: !expr '!is.null(params_df$use_milk_prod_sales) & params_df$use_milk_prod_sales == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_milk_prod_sales.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: egg production and sales
#| eval: !expr '!is.null(params_df$use_egg_prod_sales) & params_df$use_egg_prod_sales == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_egg_prod_sales.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: fisheries production and sales
#| eval: !expr '!is.null(params_df$use_fisheries_prod_sales) & params_df$use_fisheries_prod_sales == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_fisheries_prod_sales.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: aquaculture production and sales
#| eval: !expr '!is.null(params_df$use_aquaculture_prod_sales) & params_df$use_aquaculture_prod_sales == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_aquaculture_prod_sales.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: forestry production and sales
#| eval: !expr '!is.null(params_df$use_forestry_prod_sales) & params_df$use_forestry_prod_sales == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_forestry_prod_sales.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: crop processing
#| eval: !expr '!is.null(params_df$use_process_crop_prod) & params_df$use_process_crop_prod == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_process_crop_prod.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: crop labor
#| eval: !expr '!is.null(params_df$use_crop_labor) & params_df$use_crop_labor == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_crop_labor.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: livestock labor
#| eval: !expr '!is.null(params_df$use_livestock_labor_tbl) & params_df$use_livestock_labor_tbl == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_livestock_labor.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: fisheries labor
#| eval: !expr '!is.null(params_df$use_fisheries_labor) & params_df$use_fisheries_labor == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_fisheries_labor.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: aquaculture labor
#| eval: !expr '!is.null(params_df$use_aquaculture_labor) & params_df$use_aquaculture_labor == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_aquaculture_labor.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: forestry labor
#| eval: !expr '!is.null(params_df$use_forestry_labor) & params_df$use_forestry_labor == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_forestry_labor.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```

```{r}
#| label: income sources
#| eval: !expr '!is.null(params_df$use_income_sources) & params_df$use_income_sources == TRUE'
#| output: asis
cat(
  knitr::knit_child(
    text = readr::read_file("_income_sources.qmd"),
    quiet = TRUE
  ),
  sep = "\n"
)
```
